<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.10240.0</SupportedOSPlatformVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ZeitstrahlStudio.Application\ZeitstrahlStudio.Application.csproj" />
    <ProjectReference Include="..\..\src\ZeitstrahlStudio.DocumentProcessing\ZeitstrahlStudio.DocumentProcessing.csproj" />
    <ProjectReference Include="..\..\src\ZeitstrahlStudio.Domain\ZeitstrahlStudio.Domain.csproj" />
    <ProjectReference Include="..\..\src\ZeitstrahlStudio.Export\ZeitstrahlStudio.Export.csproj" />
    <ProjectReference Include="..\..\src\ZeitstrahlStudio.Infrastructure\ZeitstrahlStudio.Infrastructure.csproj" />
  </ItemGroup>

</Project>
