<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZeitstrahlStudio.Application\ZeitstrahlStudio.Application.csproj" />
    <ProjectReference Include="..\ZeitstrahlStudio.Domain\ZeitstrahlStudio.Domain.csproj" />
    <ProjectReference Include="..\ZeitstrahlStudio.Shared\ZeitstrahlStudio.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="3.119.2" />
    <PackageReference Include="SkiaSharp.NativeAssets.Win32" Version="3.119.2" />
  </ItemGroup>

</Project>
