<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.10240.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZeitstrahlStudio.Application\ZeitstrahlStudio.Application.csproj" />
    <ProjectReference Include="..\ZeitstrahlStudio.Domain\ZeitstrahlStudio.Domain.csproj" />
    <ProjectReference Include="..\ZeitstrahlStudio.Shared\ZeitstrahlStudio.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="PdfPig" Version="0.1.15" />
    <PackageReference Include="PDFtoImage" Version="5.2.1" />
  </ItemGroup>

</Project>
